general.import = ['./catpuccin/catppuccin-mocha.toml']

[env]
TERM = "xterm-256color"

[window]
opacity = 1
startup_mode = "Windowed"
dynamic_padding = false

[window.padding]
x = 4
y = 2

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"


# windows
# [shell]
# args = ["--cd ~"]
# program = 'C:\Windows\System32\wsl.exe'

# linux
[terminal.shell]
program = "/usr/bin/zsh"
